format = """
$username\
$directory\
$git_branch\
$git_status\
$lua\
$python\
$jobs\
$cmd_duration\
$line_break\
$character\
"""

[username]
show_always = true
style_user = "fg:green"
style_root = "fg:red"
format = "[$user]($style) "

[directory]
truncation_length = 4
truncation_symbol = "[...]"
truncate_to_repo = false

[git_branch]
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
style = "fg:grey"
format = "[$duration]($style)"
